# === Secret per password database ===
apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: prestiti-biblioteca
type: Opaque
data:
  # Password base64 encoded: "YourStrongPassword123!"
  # echo -n 'YourStrongPassword123!' | base64
  SA_PASSWORD: WW91clN0cm9uZ1Bhc3N3b3JkMTIzIQ==

---
# === Persistent Volume per dati database ===
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
  namespace: prestiti-biblioteca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # 10GB di storage persistente

---
# === Deployment SQL Server ===
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: prestiti-biblioteca
spec:
  replicas: 1  # SQL Server in single instance
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD
        - name: MSSQL_PID
          value: "Express"  # Usa SQL Server Express (gratuito)
        volumeMounts:
        - name: mssql-storage
          mountPath: /var/opt/mssql
        # Configurazioni per prestazioni e sicurezza
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        # Health checks
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -Q 'SELECT 1'"
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -Q 'SELECT 1'"
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: mssql-storage
        persistentVolumeClaim:
          claimName: mssql-pvc

---
# === Service per SQL Server ===
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: prestiti-biblioteca
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP  # Accessibile solo dall'interno del cluster

  